### ISSUE TITLE
forcing VM exit traced

### ISSUE THREAD

**Issue by EdLovecraft** [nbaertsch/qemu-git-patched-pkgbuild#2]
![QQ截图20200829121127](https://user-images.githubusercontent.com/40231164/91628353-676fed00-e9f1-11ea-86ba-105dee5311dd.png)

**Comment by nbaertsch** [comment]
This qemu patch is unrelated to VM exit timings.  See [BetterTiming](https://github.com/nbaertsch/BetterTiming) for offsetting timings.
